using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Gimnasio
{    
    public partial class FrmRegistroSocio : Form
    {
        private bool usoCalendario;        
        private string[,] localidades = {{"0","25 de Mayo"},
                                        {"0","Agustín Mosconi"},
                                        {"0","Del Valle"},
                                        {"0","Ernestina"},
                                        {"0","Gobernador Ugarte"},
                                        {"0","Lucas Monteverde"},
                                        {"0","Norberto de la Riestra"},
                                        {"0","Pedernales"},
                                        {"0","San Enrique"},
                                        {"0","Valdés"},
                                        {"1","12 de Octubre"},
                                        {"1","9 de Julio"},
                                        {"1","Alfredo Demarchi (Est. Facundo Quiroga)"},
                                        {"1","Carlos María Naón"},
                                        {"1","Dudignac"},
                                        {"1","La Aurora (Est. La Niña)"},
                                        {"1","Manuel B. Gonnet (Est. French)"},
                                        {"1","Marcelino Ugarte (Est. Dennehy)"},
                                        {"1","Morea"},
                                        {"1","Norumbega"},
                                        {"1","Patricios"},
                                        {"1","Villa General Fournier (Est. 9 de Julio Sud)"},
                                        {"2","Carhué"},
                                        {"2","Colonia San Miguel Arcángel"},
                                        {"2","Delfín Huergo"},
                                        {"2","Espartillar"},
                                        {"2","Esteban Agustín Gascón"},
                                        {"2","La Pala"},
                                        {"2","Maza"},
                                        {"2","Rivera"},
                                        {"2","Thames"},
                                        {"2","Villa Margarita"},
                                        {"2","Yutuyaco"},
                                        {"3","Adolfo Gonzales Chaves (Est. Chaves)"},
                                        {"3","De La Garma"},
                                        {"3","Juan E. Barra"},
                                        {"3","Vásquez"},
                                        {"4","Alberti (Est. Andrés Vaccarezza)"},
                                        {"4","Coronel Seguí"},
                                        {"4","Mechita"},
                                        {"4","Pla"},
                                        {"4","Villa Grisolía (Est. Achupallas)"},
                                        {"4","Villa María"},
                                        {"4","Villa Ortiz (Est. Coronel Mom)"},
                                        {"5","Adrogué"},
                                        {"5","Burzaco"},
                                        {"5","Claypole"},
                                        {"5","Don Orione"},
                                        {"5","Glew"},
                                        {"5","José Mármol"},
                                        {"5","Longchamps"},
                                        {"5","Malvinas Argentinas"},
                                        {"5","Ministro Rivadavia"},
                                        {"5","Rafael Calzada"},
                                        {"5","San Francisco Solano"},
                                        {"5","San José"},
                                        {"6","Arrecifes"},
                                        {"6","Todd"},
                                        {"6","Viña"},
                                        {"7","Área Cinturón Ecológico"},
                                        {"7","Avellaneda"},
                                        {"7","Crucesita"},
                                        {"7","Dock Sud"},
                                        {"7","Gerli"},
                                        {"7","Piñeyro"},
                                        {"7","Sarandí"},
                                        {"7","Villa Domínico"},
                                        {"7","Wilde"},
                                        {"8","Ayacucho"},
                                        {"8","La Constancia"},
                                        {"8","Solanet"},
                                        {"8","Udaquiola"},
                                        {"9","16 de Julio"},
                                        {"9","Ariel"},
                                        {"9","Azul"},
                                        {"9","Cacharí"},
                                        {"9","Chillar"},
                                        {"10","Bahía Blanca"},
                                        {"10","Cabildo"},
                                        {"10","General Daniel Cerri (Est. General Cerri)"},
                                        {"10","Grünbein"},
                                        {"10","Ingeniero White"},
                                        {"10","Villa Bordeau"},
                                        {"10","Villa Espora"},
                                        {"11","Balcarce"},
                                        {"11","Los Pinos"},
                                        {"11","Napaleofú "},
                                        {"11","Ramos Otero"},
                                        {"11","San Agustín"},
                                        {"11","Villa Laguna La Brava"},
                                        {"12","Baradero"},
                                        {"12","Irineo Portela"},
                                        {"12","Santa Coloma"},
                                        {"12","Villa Alsina (Est. Alsina)"},
                                        {"13","Barker"},
                                        {"13","Benito Juárez (Est. Juárez)"},
                                        {"13","López"},
                                        {"13","Tedín Uriburu"},
                                        {"13","Villa Cacique (Est. Alfredo Fortabat)"},
                                        {"14","Berazategui"},
                                        {"14","Berazategui Oeste"},
                                        {"14","Carlos Tomás Sourigues"},
                                        {"14","El Pato"},
                                        {"14","Guillermo Enrique Hudson"},
                                        {"14","Juan María Gutiérrez"},
                                        {"14","Pereyra"},
                                        {"14","Plátanos"},
                                        {"14","Ranelagh"},
                                        {"14","Villa España"},
                                        {"15","Barrio Banco Provincia"},
                                        {"15","Barrio El Carmen (este)"},
                                        {"15","Barrio Universitario"},
                                        {"15","Berisso"},
                                        {"15","Los Talas"},
                                        {"15","Villa Argüello"},
                                        {"15","Villa Dolores"},
                                        {"15","Villa Independencia"},
                                        {"15","Villa Nueva"},
                                        {"15","Villa Porteña"},
                                        {"15","Villa Progreso"},
                                        {"15","Villa San Carlos"},
                                        {"15","Villa Zula"},
                                        {"16","Hale"},
                                        {"16","Juan F. Ibarra"},
                                        {"16","Mariano Unzué"},
                                        {"16","Paula"},
                                        {"16","Pirovano"},
                                        {"16","San Carlos de Bolívar (Est. Bolívar)"},
                                        {"16","Urdampilleta"},
                                        {"16","Villa Lynch Pueyrredón"},
                                        {"17","Bragado"},
                                        {"17","Comodoro Py"},
                                        {"17","General O'Brien"},
                                        {"17","Irala"},
                                        {"17","La Limpia"},
                                        {"17","Máximo Fernández (Est. Juan F. Salaberry) "},
                                        {"17","Mechita (Est. Mecha)"},
                                        {"17","Olascoaga"},
                                        {"17","Warnes"},
                                        {"18","Altamirano"},
                                        {"18","Barrio Las Golondrinas"},
                                        {"18","Barrio Los Bosquecitos"},
                                        {"18","Barrio Parque Las Acacias"},
                                        {"18","Coronel Brandsen"},
                                        {"18","Gómez"},
                                        {"18","Jeppener"},
                                        {"18","Oliden"},
                                        {"18","Samborombón"},
                                        {"19","Alto Los Cardales"},
                                        {"19","Barrio Los Pioneros"},
                                        {"19","Campana"},
                                        {"19","Lomas del Río Luján (Est. Río Luján)"},
                                        {"20","Alejandro Petión "},
                                        {"20","Barrio Belgrano"},
                                        {"20","Barrio El Taladro"},
                                        {"20","Cañuelas"},
                                        {"20","Gobernador Udaondo"},
                                        {"20","Máximo Paz"},
                                        {"20","Santa Rosa"},
                                        {"20","Uribelarrea"},
                                        {"20","Vicente Casares "},
                                        {"21","Capitán Sarmiento"},
                                        {"21","La Luisa"},
                                        {"22","Bellocq"},
                                        {"22","Cadret"},
                                        {"22","Carlos Casares"},
                                        {"22","Colonia Mauricio"},
                                        {"22","Hortensia"},
                                        {"22","La Sofía"},
                                        {"22","Mauricio Hirsch"},
                                        {"22","Moctezuma"},
                                        {"22","Ordoqui"},
                                        {"22","Smith"},
                                        {"23","Carlos Tejedor"},
                                        {"23","Colonia Seré"},
                                        {"23","Curarú"},
                                        {"23","Timote"},
                                        {"23","Tres Algarrobos (Est. Cuenca)"},
                                        {"24","Carmen de Areco"},
                                        {"24","Pueblo Gouin"},
                                        {"24","Tres Sargentos"},
                                        {"25","Castelli"},
                                        {"25","Centro Guerrero"},
                                        {"26","Castilla"},
                                        {"26","Chacabuco"},
                                        {"26","Los Angeles"},
                                        {"26","O'Higgins"},
                                        {"26","Rawson"},
                                        {"27","Chascomús"},
                                        {"27","Chascomús Country Club"},
                                        {"27","Manuel J. Cobo (Est. Lezama)"},
                                        {"27","Villa Parque Girado"},
                                        {"28","Chivilcoy"},
                                        {"28","Emilio Ayarza"},
                                        {"28","Gorostiaga"},
                                        {"28","La Rica"},
                                        {"28","Moquehuá"},
                                        {"28","Ramón Biaus"},
                                        {"28","San Sebastián"},
                                        {"29","Comuna 1"},
                                        {"29","Comuna 10"},
                                        {"29","Comuna 11"},
                                        {"29","Comuna 12"},
                                        {"29","Comuna 13"},
                                        {"29","Comuna 14"},
                                        {"29","Comuna 15"},
                                        {"29","Comuna 2"},
                                        {"29","Comuna 3"},
                                        {"29","Comuna 4"},
                                        {"29","Comuna 5"},
                                        {"29","Comuna 6"},
                                        {"29","Comuna 7"},
                                        {"29","Comuna 8"},
                                        {"29","Comuna 9"},
                                        {"30","Colón"},
                                        {"30","El Arbolito"},
                                        {"30","Pearson"},
                                        {"30","Sarasa"},
                                        {"31","Bajo Hondo"},
                                        {"31","Balneario Pehuen Co"},
                                        {"31","Punta Alta (Est. Almirante Solier) "},
                                        {"31","Villa del Mar"},
                                        {"31","Villa General Arias (Est. Kilómetro 638)"},
                                        {"32","Aparicio"},
                                        {"32","Balneario Marisol"},
                                        {"32","Coronel Dorrego"},
                                        {"32","El Perdido (Est. José A. Guisasola)"},
                                        {"32","Faro"},
                                        {"32","Irene"},
                                        {"32","Oriente"},
                                        {"32","San Román"},
                                        {"33","Coronel Pringles (Est. Pringles)"},
                                        {"33","El Divisorio"},
                                        {"33","El Pensamiento"},
                                        {"33","Indio Rico"},
                                        {"33","Lartigau"},
                                        {"34","Cascadas"},
                                        {"34","Coronel Suárez"},
                                        {"34","Cura Malal"},
                                        {"34","D'Orbigny"},
                                        {"34","Huanguelén"},
                                        {"34","Pasman"},
                                        {"34","San José"},
                                        {"34","Santa María"},
                                        {"34","Santa Trinidad"},
                                        {"34","Villa La Arcadia"},
                                        {"35","Andant"},
                                        {"35","Arboledas"},
                                        {"35","Daireaux"},
                                        {"35","La Larga"},
                                        {"35","La Manuela"},
                                        {"35","Salazar"},
                                        {"36","Dolores"},
                                        {"36","Sevigne"},
                                        {"37","Dique Nº 1"},
                                        {"37","Ensenada"},
                                        {"37","Isla Santiago (oeste)"},
                                        {"37","Punta Lara"},
                                        {"37","Villa Catela"},
                                        {"38","Belén de Escobar"},
                                        {"38","El Cazador"},
                                        {"38","Garín"},
                                        {"38","Ingeniero Maschwitz"},
                                        {"38","Loma Verde"},
                                        {"38","Maquinista F. Savio Este"},
                                        {"38","Matheu"},
                                        {"38","Puerto Paraná"},
                                        {"39","9 de Abril"},
                                        {"39","Canning"},
                                        {"39","El Jagüel"},
                                        {"39","Luis Guillón"},
                                        {"39","Monte Grande"},
                                        {"39","Zona Aeropuerto Internacional Ezeiza"},
                                        {"40","Arroyo de la Cruz"},
                                        {"40","Capilla del Señor (Est. Capilla)"},
                                        {"40","Diego Gaynor"},
                                        {"40","El Remanso"},
                                        {"40","Los Cardales"},
                                        {"40","Parada Orlando"},
                                        {"40","Parada Robles"},
                                        {"40","Pavón"},
                                        {"41","Aeropuerto Internacional Ezeiza"},
                                        {"41","Canning"},
                                        {"41","Carlos Spegazzini"},
                                        {"41","José María Ezeiza"},
                                        {"41","La Unión"},
                                        {"41","Tristán Suárez"},
                                        {"42","Bosques"},
                                        {"42","Estanislao Severo Zeballos"},
                                        {"42","Florencio Varela"},
                                        {"42","Gobernador Julio A. Costa"},
                                        {"42","Ingeniero Juan Allan"},
                                        {"42","La Capilla"},
                                        {"42","Villa Brown"},
                                        {"42","Villa San Luis"},
                                        {"42","Villa Santa Rosa"},
                                        {"42","Villa Vatteone"},
                                        {"43","Blaquier"},
                                        {"43","Florentino Ameghino"},
                                        {"43","Porvenir"},
                                        {"44","Comandante Nicanor Otamendi"},
                                        {"44","Mar del Sur"},
                                        {"44","Mechongué"},
                                        {"44","Miramar"},
                                        {"45","General Alvear"},
                                        {"46","Arribeños"},
                                        {"46","Ascensión"},
                                        {"46","Estación Arenales"},
                                        {"46","Ferré"},
                                        {"46","General Arenales"},
                                        {"46","La Angelita"},
                                        {"46","La Trinidad"},
                                        {"47","General Belgrano"},
                                        {"47","Gorchs"},
                                        {"48","General Guido"},
                                        {"48","Labardén"},
                                        {"49","Barrio Kennedy"},
                                        {"49","General Juan Madariaga"},
                                        {"50","General La Madrid"},
                                        {"50","La Colina"},
                                        {"50","Las Martinetas"},
                                        {"50","Líbano"},
                                        {"50","Pontaut"},
                                        {"51","General Hornos"},
                                        {"51","General Las Heras (Est. Las Heras)"},
                                        {"51","La Choza"},
                                        {"51","Lozano"},
                                        {"51","Plomer"},
                                        {"51","Villars"},
                                        {"52","Chacras de San Clemente"},
                                        {"52","General Lavalle"},
                                        {"52","Pavón"},
                                        {"53","Barrio Río Salado"},
                                        {"53","Loma Verde"},
                                        {"53","Ranchos"},
                                        {"53","Villanueva  (Ap. Río Salado)"},
                                        {"54","Colonia San Ricardo (Est. Iriarte)"},
                                        {"54","General Pinto"},
                                        {"54","Germania (Est. Mayor José Orellano)"},
                                        {"54","Villa Francia (Est. Coronel Granada)"},
                                        {"54","Villa Roth (Est. Ingeniero Balbín)"},
                                        {"55","Barrio Colinas Verdes"},
                                        {"55","Barrio El Boquerón"},
                                        {"55","Barrio El Casal"},
                                        {"55","Barrio El Coyunco"},
                                        {"55","Barrio La Gloria"},
                                        {"55","Barrio Santa Paula"},
                                        {"55","Batán"},
                                        {"55","Camet"},
                                        {"55","Chapadmalal"},
                                        {"55","El Marquesado"},
                                        {"55","Estación Camet"},
                                        {"55","Estación Chapadmalal"},
                                        {"55","Mar del Plata"},
                                        {"55","Punta Mogotes"},
                                        {"55","Sierra de los Padres"},
                                        {"56","Barrio Ruta 24 Kilómetro 10"},
                                        {"56","Country Club Bosque Real - Barrio Morabo"},
                                        {"56","General Rodríguez"},
                                        {"57","Barrio Parque General San Martín"},
                                        {"57","Billinghurst"},
                                        {"57","Ciudad del Libertad General San Martín"},
                                        {"57","Ciudad Jardín El Libertador"},
                                        {"57","Villa Ayacucho"},
                                        {"57","Villa Ballester"},
                                        {"57","Villa Bernardo Monteagudo"},
                                        {"57","Villa Chacabuco"},
                                        {"57","Villa Coronel José M. Zapiola"},
                                        {"57","Villa General Antonio J. de Sucre"},
                                        {"57","Villa General Eugenio Necochea"},
                                        {"57","Villa General José Tomás Guido"},
                                        {"57","Villa General Juan G. Las Heras"},
                                        {"57","Villa Godoy Cruz"},
                                        {"57","Villa Granaderos de San Martín"},
                                        {"57","Villa Gregoria Matorras"},
                                        {"57","Villa José León Suárez"},
                                        {"57","Villa Juan Martín de Pueyrredón"},
                                        {"57","Villa Libertad"},
                                        {"57","Villa Lynch"},
                                        {"57","Villa Maipú"},
                                        {"57","Villa María Irene de los Remedios de Escalada"},
                                        {"57","Villa Marqués Alejandro María de Aguado"},
                                        {"57","Villa Parque Presidente Figueroa Alcorta"},
                                        {"57","Villa Parque San Lorenzo"},
                                        {"57","Villa San Andrés"},
                                        {"57","Villa Yapeyú"},
                                        {"58","Baigorrita"},
                                        {"58","La Delfina"},
                                        {"58","Los Toldos"},
                                        {"58","San Emilio"},
                                        {"58","Zavalía"},
                                        {"59","Banderalo"},
                                        {"59","Cañada Seca "},
                                        {"59","Coronel Charlone"},
                                        {"59","Emilio V. Bunge"},
                                        {"59","General Villegas (Est. Villegas)"},
                                        {"59","Massey (Est. Elordi)"},
                                        {"59","Pichincha"},
                                        {"59","Piedritas"},
                                        {"59","Santa Eleodora"},
                                        {"59","Santa Regina"},
                                        {"59","Villa Saboya"},
                                        {"59","Villa Sauze"},
                                        {"60","Arroyo Venado"},
                                        {"60","Casbas"},
                                        {"60","Garré"},
                                        {"60","Guaminí"},
                                        {"60","Laguna Alsina (Est. Bonifacio)"},
                                        {"61","Henderson"},
                                        {"61","Herrera Vegas"},
                                        {"62","Hurlingham"},
                                        {"62","Villa Santos Tesei"},
                                        {"62","William C. Morris"},
                                        {"63","Ituzaingó Centro"},
                                        {"63","Ituzaingó Sur"},
                                        {"63","Villa Gobernador Udaondo"},
                                        {"64","Del Viso"},
                                        {"64","José C. Paz"},
                                        {"64","Tortuguitas"},
                                        {"65","Agustín Roca"},
                                        {"65","Agustina"},
                                        {"65","Balneario Laguna de Gómez"},
                                        {"65","Fortín Tiburcio"},
                                        {"65","Junín"},
                                        {"65","Laplacette"},
                                        {"65","Morse"},
                                        {"65","Saforcada"},
                                        {"66","Aguas Verdes"},
                                        {"66","Las Toninas"},
                                        {"66","Lucila del Mar"},
                                        {"66","Mar de Ajó"},
                                        {"66","Mar de Ajó Norte"},
                                        {"66","Mar del Tuyú"},
                                        {"66","San Bernardo"},
                                        {"66","San Clemente del Tuyú"},
                                        {"66","Santa Teresita"},
                                        {"67","20 de Junio"},
                                        {"67","Aldo Bonzi"},
                                        {"67","Ciudad Evita"},
                                        {"67","González Catán"},
                                        {"67","Gregorio de Laferrere"},
                                        {"67","Isidro Casanova"},
                                        {"67","La Tablada"},
                                        {"67","Lomas del Mirador"},
                                        {"67","Rafael Castillo"},
                                        {"67","Ramos Mejía"},
                                        {"67","San Justo"},
                                        {"67","Tapiales"},
                                        {"67","Villa  Eduardo Madero"},
                                        {"67","Villa Luzuriaga"},
                                        {"67","Virrey del Pino"},
                                        {"68","Abasto"},
                                        {"68","Angel Etcheverry"},
                                        {"68","Arana"},
                                        {"68","Arturo Segui"},
                                        {"68","Barrio El Carmen (oeste)"},
                                        {"68","Barrio Gambier"},
                                        {"68","Barrio Las Malvinas"},
                                        {"68","Barrio Las Quintas"},
                                        {"68","City Bell"},
                                        {"68","Country Club El Rodeo"},
                                        {"68","El Retiro"},
                                        {"68","Ignacio Correas"},
                                        {"68","Joaquín Gorina"},
                                        {"68","José Hernández"},
                                        {"68","José Melchor Romero"},
                                        {"68","La Cumbre"},
                                        {"68","La Plata"},
                                        {"68","Lisandro Olmos"},
                                        {"68","Lomas de Copello"},
                                        {"68","Los Hornos"},
                                        {"68","Manuel B. Gonnet"},
                                        {"68","Ringuelet"},
                                        {"68","Rufino de Elizalde"},
                                        {"68","Ruta Sol"},
                                        {"68","Tolosa"},
                                        {"68","Transradio"},
                                        {"68","Villa Elisa"},
                                        {"68","Villa Elvira"},
                                        {"68","Villa Garibaldi"},
                                        {"68","Villa Montoro"},
                                        {"68","Villa Parque Sicardi"},
                                        {"69","Gerli"},
                                        {"69","Lanús Este"},
                                        {"69","Lanús Oeste"},
                                        {"69","Monte Chingolo"},
                                        {"69","Remedios Escalada de San Martín"},
                                        {"69","Valentín Alsina"},
                                        {"70","Laprida"},
                                        {"70","Pueblo Nuevo"},
                                        {"70","Pueblo San Jorge"},
                                        {"71","Coronel Boerr"},
                                        {"71","El Trigo"},
                                        {"71","Las Flores"},
                                        {"71","Pardo"},
                                        {"72","Alberdi Viejo"},
                                        {"72","El Dorado"},
                                        {"72","Fortín Acha"},
                                        {"72","Juan Bautista Alberdi (Est. Alberdi)"},
                                        {"72","Leandro N. Alem"},
                                        {"72","Vedia"},
                                        {"73","Arenaza"},
                                        {"73","Bayauca"},
                                        {"73","Bermúdez"},
                                        {"73","Carlos Salas"},
                                        {"73","Coronel Martínez de Hoz (Ap. Kilómetro 322)"},
                                        {"73","El Triunfo"},
                                        {"73","Las Toscas"},
                                        {"73","Lincoln"},
                                        {"73","Pasteur"},
                                        {"73","Roberts"},
                                        {"74","Arenas Verdes"},
                                        {"74","Licenciado Matienzo"},
                                        {"74","Lobería"},
                                        {"74","Pieres"},
                                        {"74","San Manuel"},
                                        {"74","Tamangueyú"},
                                        {"75","Antonio Carboni"},
                                        {"75","Elvira"},
                                        {"75","Laguna de Lobos"},
                                        {"75","Lobos"},
                                        {"75","Salvador María"},
                                        {"76","Bandfield"},
                                        {"76","Llavallol"},
                                        {"76","Lomas de Zamora"},
                                        {"76","Temperley"},
                                        {"76","Turdera"},
                                        {"76","Villa Centenario"},
                                        {"76","Villa Fiorito"},
                                        {"77","Barrio Las Casuarinas"},
                                        {"77","Carlos Keen"},
                                        {"77","Cortines"},
                                        {"77","Country Club Las Praderas"},
                                        {"77","Lezica y Torrezuri"},
                                        {"77","Luján"},
                                        {"77","Olivera"},
                                        {"77","Open Door"},
                                        {"77","Torres"},
                                        {"77","Villa Flandria Norte"},
                                        {"77","Villa Flandria Sur"},
                                        {"78","Atalaya"},
                                        {"78","General Mansilla (Est. Bartolomé Bavio)"},
                                        {"78","Los Naranjos"},
                                        {"78","Magdalena"},
                                        {"78","Roberto J. Payró"},
                                        {"78","Vieytes"},
                                        {"79","Las Armas"},
                                        {"79","Maipú"},
                                        {"79","Santo Domingo"},
                                        {"80","Area de Promoción El Triángulo"},
                                        {"80","Grand Bourg"},
                                        {"80","Ingeniero Adolfo Sourdeaux"},
                                        {"80","Ingeniero Pablo Nogués"},
                                        {"80","Los Polvorines"},
                                        {"80","Malvinas Argentinas"},
                                        {"80","Tortuguitas"},
                                        {"80","Villa de Mayo"},
                                        {"81","Atlántida"},
                                        {"81","Camet Norte"},
                                        {"81","Coronel Vidal"},
                                        {"81","Frente Mar"},
                                        {"81","General Pirán"},
                                        {"81","La Armonía"},
                                        {"81","La Baliza"},
                                        {"81","La Caleta"},
                                        {"81","Mar Chiquita"},
                                        {"81","Mar de Cobo"},
                                        {"81","Playa Dorada"},
                                        {"81","Santa Clara del Mar"},
                                        {"81","Santa Elena"},
                                        {"81","Vivoratá"},
                                        {"82","Barrio Santa Rosa"},
                                        {"82","Barrios Lisandro de la Torre y Santa Marta"},
                                        {"82","Marcos Paz"},
                                        {"83","Gowland"},
                                        {"83","Mercedes"},
                                        {"83","Tomás Jofré"},
                                        {"84","Libertad"},
                                        {"84","Mariano Acosta"},
                                        {"84","Merlo"},
                                        {"84","Pontevedra"},
                                        {"84","San Antonio de Padua"},
                                        {"85","Abbott"},
                                        {"85","San Miguel del Monte (Est. Monte)"},
                                        {"85","Zenón Videla Dorna"},
                                        {"86","Balneario Sauce Grande"},
                                        {"86","Monte Hermoso"},
                                        {"87","Cuartel V"},
                                        {"87","Francisco Álvarez"},
                                        {"87","La Reja"},
                                        {"87","Moreno"},
                                        {"87","Paso del Rey"},
                                        {"87","Trujui"},
                                        {"88","Castelar"},
                                        {"88","El Palomar"},
                                        {"88","Haedo"},
                                        {"88","Morón"},
                                        {"88","Villa Sarmiento"},
                                        {"89","José Juan Almeyra"},
                                        {"89","Las Marianas"},
                                        {"89","Navarro"},
                                        {"89","Villa Moll (Est. Moll)"},
                                        {"90","Claraz"},
                                        {"90","Costa Bonita"},
                                        {"90","Juan N. Fernández"},
                                        {"90","Necochea"},
                                        {"90","Nicanor Olivera (Est. La Dulce)"},
                                        {"90","Quequén"},
                                        {"90","Ramón Santamarina"},
                                        {"91","Blancagrande"},
                                        {"91","Colonia Hinojo "},
                                        {"91","Colonia Nievas"},
                                        {"91","Colonia San Miguel"},
                                        {"91","Espigas"},
                                        {"91","Hinojo "},
                                        {"91","Olavarría"},
                                        {"91","Recalde"},
                                        {"91","Santa Luisa"},
                                        {"91","Sierra Chica"},
                                        {"91","Sierras Bayas "},
                                        {"91","Villa Alfredo Fortabat "},
                                        {"91","Villa Arrieta"},
                                        {"91","Villa La Serranía"},
                                        {"92","Bahía San Blas"},
                                        {"92","Cardenal Cagliero"},
                                        {"92","Carmen de Patagones "},
                                        {"92","José B. Casas"},
                                        {"92","Juan A. Pradere"},
                                        {"92","Stroeder"},
                                        {"92","Villalonga"},
                                        {"93","Capitán Castro"},
                                        {"93","Chiclana"},
                                        {"93","Francisco Madero"},
                                        {"93","Juan José Paso"},
                                        {"93","Magdala"},
                                        {"93","Mones Cazón"},
                                        {"93","Nueva Plata"},
                                        {"93","Pehuajó"},
                                        {"93","San Bernardo (Est. Guanaco)"},
                                        {"94","Bocayuva"},
                                        {"94","De Bary"},
                                        {"94","Pellegrini"},
                                        {"95","Acevedo"},
                                        {"95","Fontezuela"},
                                        {"95","Guerrico"},
                                        {"95","Juan A. de la Peña"},
                                        {"95","Juan Anchorena (Est. Urquiza)"},
                                        {"95","La Violeta"},
                                        {"95","Manuel Ocampo"},
                                        {"95","Mariano Benítez"},
                                        {"95","Mariano H. Alfonzo (Est. San Patricio)"},
                                        {"95","Pergamino"},
                                        {"95","Pinzón"},
                                        {"95","Rancagua"},
                                        {"95","Villa Angélica (Est. El Socorro)"},
                                        {"95","Villa San José"},
                                        {"96","Casalins"},
                                        {"96","Pila"},
                                        {"97","Barrio Parque Almirante Irizar (Ap. Kilómetro 61) "},
                                        {"97","Club de Campo Larena - Los Quinchos"},
                                        {"97","Country Club El Jagüel "},
                                        {"97","Del Viso"},
                                        {"97","Fátima"},
                                        {"97","La Lonja"},
                                        {"97","Los Cachorros"},
                                        {"97","Manzanares"},
                                        {"97","Manzone"},
                                        {"97","Maquinista F. Savio Oeste"},
                                        {"97","Pilar"},
                                        {"97","Presidente Derqui"},
                                        {"97","Roberto de Vicenzo"},
                                        {"97","Santa Teresa"},
                                        {"97","Tortuguitas"},
                                        {"97","Villa Astolfi"},
                                        {"97","Villa Rosa"},
                                        {"97","Zelaya"},
                                        {"98","Cariló"},
                                        {"98","Ostende"},
                                        {"98","Pinamar"},
                                        {"98","Valeria del Mar"},
                                        {"99","Barrio América Unida"},
                                        {"99","Guernica"},
                                        {"100","17 de Agosto"},
                                        {"100","Azopardo"},
                                        {"100","Bordenave"},
                                        {"100","Darregueira"},
                                        {"100","Estela"},
                                        {"100","Felipe Solá"},
                                        {"100","López Lecube"},
                                        {"100","Puán"},
                                        {"100","San Germán"},
                                        {"100","Villa Castelar (Est. Erize)"},
                                        {"100","Villa Iris"},
                                        {"101","Alvarez Jonte"},
                                        {"101","Las Tahonas"},
                                        {"101","Pipinas"},
                                        {"101","Punta Indio"},
                                        {"101","Verónica"},
                                        {"102","Bernal"},
                                        {"102","Bernal Oeste"},
                                        {"102","Don Bosco"},
                                        {"102","Ezpeleta"},
                                        {"102","Ezpeleta Oeste"},
                                        {"102","Quilmes"},
                                        {"102","Quilmes Oeste"},
                                        {"102","San Francisco Solano"},
                                        {"102","Villa La Florida"},
                                        {"103","El Paraíso"},
                                        {"103","Las Bahamas"},
                                        {"103","Pérez Millán"},
                                        {"103","Ramallo"},
                                        {"103","Villa General Savio (Est. Sánchez)"},
                                        {"103","Villa Ramallo"},
                                        {"104","Rauch"},
                                        {"105","América"},
                                        {"105","Fortín Olavarría"},
                                        {"105","Gonzalez Moreno"},
                                        {"105","Mira Pampa"},
                                        {"105","Roosevelt"},
                                        {"105","San Mauricio"},
                                        {"105","Sansinena"},
                                        {"105","Sundblad"},
                                        {"106","La Beba"},
                                        {"106","Las Carabelas"},
                                        {"106","Los Indios"},
                                        {"106","Rafael Obligado"},
                                        {"106","Roberto Cano"},
                                        {"106","Rojas"},
                                        {"106","Sol de Mayo"},
                                        {"106","Villa Manuel Pomar"},
                                        {"106","Villa Parque Cecir"},
                                        {"107","Carlos Beguerie"},
                                        {"107","Roque Pérez"},
                                        {"108","Arroyo Corto"},
                                        {"108","Colonia San Martín"},
                                        {"108","Dufaur"},
                                        {"108","Espartillar"},
                                        {"108","Goyena"},
                                        {"108","Pigüé"},
                                        {"108","Saavedra"},
                                        {"109","Álvarez de Toledo"},
                                        {"109","Blaquier"},
                                        {"109","Cazón"},
                                        {"109","Del Carril"},
                                        {"109","Polvaredas"},
                                        {"109","Saladillo"},
                                        {"110","Quenumá"},
                                        {"110","Salliqueló"},
                                        {"111","Arroyo Dulce"},
                                        {"111","Berdier"},
                                        {"111","Gahan"},
                                        {"111","Inés Indart"},
                                        {"111","La Invencible"},
                                        {"111","Salto"},
                                        {"112","Azcuénaga"},
                                        {"112","Cucullú"},
                                        {"112","Franklin"},
                                        {"112","San Andrés de Giles"},
                                        {"112","Solís"},
                                        {"112","Villa Espil"},
                                        {"112","Villa Ruiz"},
                                        {"113","Duggan "},
                                        {"113","San Antonio de Areco"},
                                        {"113","Villa Lía"},
                                        {"114","Balneario San Cayetano"},
                                        {"114","Ochandío"},
                                        {"114","San Cayetano"},
                                        {"115","San Fernando"},
                                        {"115","Victoria"},
                                        {"115","Virreyes"},
                                        {"116","Acassuso"},
                                        {"116","Béccar"},
                                        {"116","Boulogne Sur Mer"},
                                        {"116","Martínez"},
                                        {"116","San Isidro"},
                                        {"116","Villa Adelina"},
                                        {"117","Bella Vista"},
                                        {"117","Campo de Mayo"},
                                        {"117","Muñiz"},
                                        {"117","San Miguel"},
                                        {"118","Campos Salles"},
                                        {"118","Conesa"},
                                        {"118","Erezcano"},
                                        {"118","General Rojo"},
                                        {"118","La Emilia"},
                                        {"118","San Nicolás de los Arroyos "},
                                        {"118","Villa Campi"},
                                        {"118","Villa Canto"},
                                        {"118","Villa Esperanza"},
                                        {"118","Villa Hermosa"},
                                        {"119","Gobernador Castro"},
                                        {"119","Obligado"},
                                        {"119","Pueblo Doyle"},
                                        {"119","Río Tala"},
                                        {"119","San Pedro"},
                                        {"119","Santa Lucía"},
                                        {"120","Alejandro Korn"},
                                        {"120","Domselaar"},
                                        {"120","San Vicente"},
                                        {"121","General Rivas"},
                                        {"121","Suipacha"},
                                        {"122","De la Canal"},
                                        {"122","Desvío Aguirre"},
                                        {"122","Gardey"},
                                        {"122","María Ignacia (Est. Vela)"},
                                        {"122","Tandil"},
                                        {"123","Crotto"},
                                        {"123","Tapalqué"},
                                        {"123","Velloso"},
                                        {"124","Benavídez"},
                                        {"124","Dique Luján"},
                                        {"124","Don Torcuato Este"},
                                        {"124","Don Torcuato Oeste"},
                                        {"124","El Talar"},
                                        {"124","General Pacheco"},
                                        {"124","Los Troncos del Talar"},
                                        {"124","Ricardo Rojas"},
                                        {"124","Rincón de Milberg"},
                                        {"124","Tigre"},
                                        {"125","General Conesa"},
                                        {"125","Villa Roch"},
                                        {"126","Chasicó"},
                                        {"126","Saldungaray"},
                                        {"126","Sierra de la Ventana"},
                                        {"126","Tornquist"},
                                        {"126","Tres Picos"},
                                        {"126","Villa Las Encadenadas"},
                                        {"126","Villa Serrana La Gruta"},
                                        {"126","Villa Ventana"},
                                        {"127","30 de Agosto"},
                                        {"127","Berutti"},
                                        {"127","Girodias"},
                                        {"127","La Carreta"},
                                        {"127","Trenque Lauquen"},
                                        {"127","Trongé"},
                                        {"128","Balneario Orense"},
                                        {"128","Claromecó"},
                                        {"128","Copetonas"},
                                        {"128","Dunamar"},
                                        {"128","Lin Calel"},
                                        {"128","Micaela Cascallares (Est. Cascallares)"},
                                        {"128","Orense"},
                                        {"128","Reta"},
                                        {"128","San Francisco de Bellocq"},
                                        {"128","San Mayol"},
                                        {"128","Tres Arroyos"},
                                        {"128","Villa Rodríguez (Est. Barrow)"},
                                        {"129","11 de Septiembre"},
                                        {"129","Caseros"},
                                        {"129","Churruca"},
                                        {"129","Ciudad Jardín Lomas del Palomar"},
                                        {"129","Ciudadela"},
                                        {"129","El Libertador"},
                                        {"129","José Ingenieros"},
                                        {"129","Loma Hermosa"},
                                        {"129","Martín Coronado"},
                                        {"129","Pablo Podestá"},
                                        {"129","Remedios de Escalada"},
                                        {"129","Saénz Peña"},
                                        {"129","Santos Lugares"},
                                        {"129","Villa Bosch (Est. Juan María Bosch)"},
                                        {"129","Villa Raffo"},
                                        {"130","Ingeniero Thompson"},
                                        {"130","Tres Lomas "},
                                        {"131","Carapachay"},
                                        {"131","Florida"},
                                        {"131","Florida Oeste"},
                                        {"131","La Lucila"},
                                        {"131","Munro"},
                                        {"131","Olivos"},
                                        {"131","Vicente López"},
                                        {"131","Villa Adelina"},
                                        {"131","Villa Martelli"},
                                        {"132","Mar Azul"},
                                        {"132","Mar de las Pampas"},
                                        {"132","Villa Gesell "},
                                        {"133","Argerich"},
                                        {"133","Colonia San Adolfo"},
                                        {"133","Country Los Médanos"},
                                        {"133","Hilario Ascasubi"},
                                        {"133","Juan Cousté (Est. Algarrobo)"},
                                        {"133","Mayor Buratovich"},
                                        {"133","Médanos"},
                                        {"133","Pedro Luro"},
                                        {"133","Teniente Origone"},
                                        {"134","Barrio Saavedra"},
                                        {"134","Country Club El Casco"},
                                        {"134","Escalada"},
                                        {"134","Lima"}
        };
        public FrmRegistroSocio()
        {
            InitializeComponent();
            usoCalendario = false;            
        }
        public bool EstanLosCamposCompletos() 
        {
            string a = inpNombre.Text;
            string b = inpApellido.Text;
            string c = inpDireccion.Text;
            int d = Convert.ToInt32( inpNumero.Value );
            string e = cmbPartido.Text;
            string f = cmbLocalidad.Text;
            return (a == "" || b == "" || c == "" || d == 0 || e == "" || f == "") ? false : true;            
        }
        private void btnCancelar_Click(object sender, EventArgs e)
        {
            BlanqueoRegistro();
            inpNombre.Focus();
            Program.s.frmDetalleSocios.Show();
            this.Hide();
        }
        private void cmbPartido_SelectedIndexChanged(object sender, EventArgs e)
        {
            int index = cmbPartido.SelectedIndex;
            cmbLocalidad.Text = "";
            cmbLocalidad.Items.Clear();
            for(int i = 0; i < localidades.GetLength(0); i++)
            {
                if(index == Convert.ToInt32(localidades[i, 0]))
                {
                    cmbLocalidad.Items.Add(localidades[i, 1]);
                }                
            }            
        }
        private bool HayEdadValida()
        {
            int anioActual = Convert.ToInt32(DateTime.Today.Year);
            int anioElegido = dtpNacimiento.Value.Year;
            if (anioActual - anioElegido < 21)
            {
                MessageBox.Show("Edad no válida. Tiene que ser mayor a 21 años", "Dato erróneo");
                return false;
            }
            else
            {
                return true;                
            }
        }        
        private void btnCrearSocio_Click(object sender, EventArgs e)
        {
            if (!EstanLosCamposCompletos())
            {
                MessageBox.Show("Faltan campos por completar", "Faltante");
                return;
            }
            if (!usoCalendario)
            {
                MessageBox.Show("Debe ingresar una fecha de nacimiento", "Faltante");
                return;
            }
            if (!HayDniValido())
            {
                MessageBox.Show("DNI ya existente en la base!", "Error");
                return;
            }
            if (!HayEdadValida())
            {
                MessageBox.Show("La edad seleccionada no es válida", "No autorizado");
                return;
            }
            if( MessageBox.Show("Está seguro que los datos son correctos?", "Confirmación", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                CrearSocio();
                BlanqueoRegistro();
                inpNombre.Focus();
                if (MessageBox.Show("Desea continuar con la carga de socios?", "Continuar", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.No)
                {
                    Program.s.frmDetalleSocios.Show();
                    this.Hide();
                }
            }
            else
            {
                MessageBox.Show("Puede corregirlos","Corrección");
            }
        }
        private void BlanqueoRegistro()
        {
            inpNombre.Text = null;
            inpApellido.Text = null;
            inpDireccion.Text = null;
            inpNumero.Value = 0;
            inpDni.Value = 10000000;
            usoCalendario = false;
            cmbPartido.Text = "";
            cmbLocalidad.Text = "";
            cmbLocalidad.Items.Clear();
            pbImagen.Image = null;
        }
        private void CrearSocio()
        {
            string a = inpNombre.Text;
            string b = inpApellido.Text;
            int dia = dtpNacimiento.Value.Day;
            int mes = dtpNacimiento.Value.Month;
            int anio = dtpNacimiento.Value.Year;
            Fecha c= new Fecha(dia, mes, anio);
            string d = inpDireccion.Text;
            int e = Convert.ToInt32(inpNumero.Value);
            int f = Convert.ToInt32(inpDni.Value);            
            string g = cmbPartido.Text;
            string h = cmbLocalidad.Text;
            Image i = pbImagen.Image;
            Program.a.baseSocios.AgregarSocioMasDni(a, b, c, d, e, f, g, h, i);
            Program.s.frmDetalleSocios.RefrescarGrid();
            Program.s.frmActividad.RefrescarGridSocios();
            Program.GuardarBaseDatos();
            MessageBox.Show("Socio creado con éxito!","Nuevo socio");
        }
        private bool HayDniValido()
        {
            int doc = Convert.ToInt32(inpDni.Value);
            if (Program.a.baseSocios.ExisteDni(doc))
            {                
                lblDocumento.Visible = true;
                lblDocumento.Text = "Socio existente!";
                return false;
            }
            else
            {
                lblDocumento.Visible = false;
                return true;
            }
        }
        private void inpDni_TabIndexChanged(object sender, EventArgs e)
        {
            HayDniValido();
        }
        private void dtpNacimiento_Leave(object sender, EventArgs e)
        {
            HayEdadValida();
        }
        private void dtpNacimiento_KeyDown(object sender, KeyEventArgs e)
        {
            usoCalendario = true;
        }
        private void btnCargaImagen_Click(object sender, EventArgs e)
        {            
            if (ofdImagen.ShowDialog()== DialogResult.OK)
            {
                pbImagen.Image = Image.FromFile(ofdImagen.FileName);                
            }
        }
    }
}
